### PR TITLE
Workaround for Polymer SVG issue

### PR DESCRIPTION
**Pull request by MikeTheReader**
This change modifies stylesheets included in context.stylesheets to replace any single quote characters (`'`) in url expressions with `%27`. This addresses an issue with Polymer dropping single quote characters in url expressions related to https://github.com/Polymer/polymer/issues/1276.

### CODE REVIEW

**Comment by MikeTheReader** [comment]
Good point. Looking at my own non-SVG URLs, I'm only using double-quotes, so it didn't affect any of my styles. Modified the regex and the tests.

**Comment by straker** [comment]
Much better. However, the regex is still a bit too greedy. It will break the 2nd url on this entry: `url("data:image/svg+xml;..."), url('https://mdn.mozillademos.org/files/7693/catfront.png')`. If you change the regex `.*` to `[^)]*` then it will only group one url at a time.

**Comment by MikeTheReader** [comment]
Fixed. Added test for that particular case as well. Thanks.

**Comment by straker** [comment]
So... Sorry to say we're *so* close but I have another test case it fails on. An svg that uses a property such as `transform` or `matrix` will end the regex early: `url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='13' height='13'><g transform='translate(-1, -1)'><path d='M13 2L2 13M2 2L13 13' stroke='#333331' stroke-width='2.5'/></g></svg>")`. 

So I think this regex might handle all cases `url\("data:image\/svg\+xml;.*?"\)`

**Comment by straker** [comment]
Can't think of any other edge cases. Great work.

**Pull request merged**
