### PR TITLE
fix(styles) prevent styles from cascading to examples

### LINKED ISSUE #17: Overriding default styles from template
So I want to retain most everything in the default template except the `mainStylesheet` partial (as it resets some of my global styles which I'd rather not do). In fact, I'd argue that only what is in that partial should be namespaced with .livingcss and anything that could possibly be global not include which would make this even easier, but alas.

What is the best way to replace only this portion? I don't want all the resets that happen there but I do want the rest of the styles for the style guide portions.  The only thing I can think of is re-creating the templates directory/files in my code and ripping it out of there and pointing the template to my directory instead.  The problem with that is updates to these files will no longer cascade to me and every time I update livingcss I'd have to do the copying over to my files, rip out styles i don't need from mainStylesheet partial, etc.

What is the best way forward for this?

### PR DESCRIPTION
**Pull request by straker**
fixes #17

### CODE REVIEW

**Comment by reintroducing** [comment]
As I said in the issue I don't know how to pull this branch in as a dep of gulp-livingcss but i just looked over your changes here. I think you're still going to run into issues because you're setting the font size on `html`. This will cause anyone using rems as font-sizing to inherit from the root which in this case will be 14px but, for instance, my project depends on 16px as the default.

I actually just ran into this at my "day job" as we had set 62.5% on html and we use Sass to pull in base styles. Well, we are now developing a third party widget and I was pulling in our base styles and then realized I'm going to affect people's CSS on the page because I'm setting a font size on html. The way I'm solving it (at least I think I am, still in development :) is by scoping my html element to something like `namespace-html` as the class name. I'm then targeting that namespace when setting global elements rather than the html tag itself. We have two ways to init the widget, as an iframe (in which case none of this matters because it has its own DOM) and as a JS version in which case this does matter because the html will just be spit out straight onto a page and templated out. In the case of the JS version I will just add the `namespace-html` class onto the containing div and that will contain the styles. I also had to update our font-size mixin specifically for the widget to not use rems when spitting out the font sizes because if it did then it would still inherit from the root html of whatever page it was put on and our fonts would look completely off as they'd be based on whatever the html setting is for that brand's html tag.

I may have gotten into a ramble here so hopefully that all made sense :\

**Comment by straker** [comment]
You can pull down the branch by navigating to `node_modules/gulp-livingcss` and editing the `package.json` file and changing the `livingcss` dependency, then do `npm install` in that same directory and it should pull down the new version.

As for the font, I'm ok with that one. I fully expect most style guides to incorporate their own font size, and if not then at least they will get a decent one as a base. But that's easy enough to override. I'd rather not add a selector that makes overrides harder since any class selector will increase the specificity to that above a tag, which is the most common way to style the html and body tags.

**Comment by reintroducing** [comment]
Disregard my drivel up there about the widget, it completely doesn't apply here because its the other way around in the workflow, not sure why I wrote all that :)

Regarding your changes, they seem to be working correctly so thank you for that. One thing I am noticing, however, is the following: https://www.dropbox.com/s/7oio3byhivmj7le/Screenshot%202016-08-07%2007.36.10.png?dl=0

That's the first section and subsection in my guide.  Further down (after the first example of that heading section) I have another set of subsections in Typography that look the same with the tiny font (these are just test sections but you get the idea) and then the next section, which is Placeholders (twice because I actually haven't documented anything correctly yet but those comments are in there as carryovers from another project where I was using those placeholders) looks like this: https://www.dropbox.com/s/bmy7skgbg93f2if/Screenshot%202016-08-07%2007.38.21.png?dl=0

Those are the correct font size (the descriptions) and I would expect the Typography section to have that same font size as well.  When I inspect them the correctly sized descriptions live in a div with the class `livingcss__section-description` while the tiny ones live in a div with a p inside of it with that same classname.  Not sure why one would be applying to a div and the other to a wrapped p inside there but thought I'd point it out.

**Comment by straker** [comment]
Sorry I haven't replied sooner, I went on vacation and just got back. So I looked through the code, and the only place I use the `livingcss__section-description` is in a div. However, when you use markdown in the description, it likes to surround everything with a `<p>` tag, so I bet that's where the p came from.

**Comment by reintroducing** [comment]
I too just got back from vacation :)  I'll take a look at this when I get a chance, have to catch myself back up on everything. Thanks.

**Pull request merged**
